### ISSUE TITLE
contract transaction was not accepted transaction set is too large for this transaction pool

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#11]
We get many of this warning here

https://github.com/lukechampine/muse/blob/ce8e2212ad17dba87f64cb0d20369bdf63781d8d/server.go#L149

Ideally, it'd be fine because at least the host could broadcast the contract transaction before responding to the form request. However, we also get `no contract record` error from hosts, which means the host doesn't have the contract. 
If a transaction set is too large for our transaction pool, it seems too large for the host's transaction pool because a host would receive more transactions than a renter has.

Would it be possible that both renter and host don't broadcast the contract transaction but finish the protocol without any error? Then, the host doesn't store the contract but the renter keeps it as an active contract.

**Comment by lukechampine** [comment]
This is one of the unfortunate edge cases of contract formation. The host doesn't reject the contract, because the contract itself is fine; it just can't get it into a block. The host will hold onto the contract, wait a while, and try submitting it to the transaction pool again. It keeps doing this until it succeeds or until the contract is rejected as invalid (which can happen if the inputs used in the contract are spent in a different transaction).

Do you get `no record of that contract` immediately after forming the contract, or does it take a while?

**Comment by jkawamoto** [comment]
We form contracts in advance and don't use them immediately after forming the contract. So, I'm not sure when a contract is removed from a host. We try to lock a contract before using it. Log shows we could lock some contracts but later it returns "no record of that contract". That means it took a while until they got removed.

If a renewed contract is removed from a host, we cannot get data from the host since the previous contract is already finalized. Is that correct? Or, the host rolls back the previous contract when it removes the renewed contract?

**Comment by jkawamoto** [comment]
I got the same error on Sia Central's lite wallet and I think this commit fixed the error: https://github.com/siacentral/sia-lite-wallet-web/commit/c6bb76ee8aa5848d5bd27f0c10b5d659f53f394b.
