### ISSUE TITLE
Option flag to specify internal Walrus address in full node mode

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#2]
Currently, the internal Walrus address is randomly chosen, but unfortunately, it doesn't work with Kubernetes. It'd be nice if it supports an option flag to specify the address. Perhaps, `-wl` is good.

**Comment by lukechampine** [comment]
ok, this should do the trick: https://github.com/lukechampine/muse/commit/91294ab90ff38c4ca7ae5bd03fd77fd0963dcd18

You must now specify `--serve-walrus` and `--serve-shard` if you want to start a new server rather than connect to an existing one. Maybe it should be reversed (so that serving is the default), idk. But this should be sufficient for now.
