### ISSUE TITLE
Question about scalability

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#6]
The server has all contracts with a slice and searches a contract sequentially. It might cause a performance issue if the client forms tens of thousands of contracts. Is there any plan to use some scalable database instead?

**Comment by lukechampine** [comment]
Searching shouldn't be an issue; I ran a quick benchmark, and you can iterate over 1 million contracts 200 times per second. Memory usage doesn't seem like a big deal either: each contract requires about 100 B, so that's 100 MB RAM per 1 million contracts.

Currently `muse` saves each contract as a separate JSON file, so if you get up to 1 million contracts, that could be an issue. The JSON contracts are a bit larger (conservatively 500 B), so 1 million contracts is 500 MB disk space. More importantly, some filesystems can't handle storing 1 million files in the same directory. If we start to approach those limits, I can switch to a database without much trouble.
