### ISSUE TITLE
Forming a contract takes a long time

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#9]
I'm not sure what's going on but forming a contract takes at least one minute and sometimes takes more than one hour:
![2020-09-08](https://user-images.githubusercontent.com/1793096/92442778-76d40080-f17e-11ea-8ffd-bca48d8a14ba.png)

An elapsed time in the above image shows how long one `Client.Form` took.

**Comment by lukechampine** [comment]
wow, and all of those succeeded?

It can't be due to the host, because `FormContract` sets a connection deadline of 2 minutes. That means the time must be spent somewhere else in the `handleForm` method. It's possible that this is caused by the mutex I added recently; if a bunch of contracts are being formed at the same time, they'll be serialized, so you'd expect to see increasing formation times. I suggest adding some printlns to `handleForm` to see where time is being spent.

**Comment by jkawamoto** [comment]
They were succeeded. I'll add logs.
